{
 "title": "SJG: Cardano-Node",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<center><a href=\"https://spojapanguild.net/\" target=\"_blank\"><img width=\"250px\" src=\"https://user-images.githubusercontent.com/80967103/177022216-2ef7792b-686e-4110-b001-b6282e4bfa20.png\"></a><br>\n<img width=\"20px\" src=\"https://www.lvlup-stakepool.com/images/adapool.png\"> \n<a href=\"https://cexplorer.io/list/0cd4240a78676d56\" target=\"_blank\">Alliance List\nSJG</a></center>\n<center><a href=\"https://docs.spojapanguild.net/\" target=\"_blank\">SPO JAPAN GUILD DOCS</a></center>\n"
   },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Minted blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{instance=\"localhost:12798\"}",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{instance=\"localhost:12798\"}/1440/60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "KES残り日数",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int * 1.5)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Change kes timing(startKesPeriod)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{instance=\"localhost:12798\"} / 129600",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Key rotation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int",
     "legendFormat": "現在のKES"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int",
     "legendFormat": "KES満了"
    },
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int - cardano_node_metrics_operationalCertificateStartKESPeriod_int + cardano_node_metrics_remainingKESPeriods_int",
     "legendFormat": "KES整合性"
    },
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int",
     "legendFormat": "KES残"
    }
   ]
  },
  {
   "title": "Txs processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "1 Second block fetch client block delay",
   "type": "stat",
   "description": "■ブロックの伝搬について\n1秒、3秒、5秒以内にブロックをダウンロードできたおおよその推定値\n95%のブロックを3秒以内にダウンロードしていれば、よく稼働しているノード指標となります。\n95%のブロックを5秒以内にダウンロードすることは、ウロボロスPraosのセキュリティ上の最低ラインとなります。\n※ノードを再起動すると初期化されますので適正値になるまで時間がかかります。",
   "gridPos": { "h": 6, "w": 1, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfOne",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "3 Second block fetch client block delay",
   "type": "stat",
   "description": "■ブロックの伝搬について\n1秒、3秒、5秒以内にブロックをダウンロードできたおおよその推定値\n95%のブロックを3秒以内にダウンロードしていれば、よく稼働しているノード指標となります。\n95%のブロックを5秒以内にダウンロードすることは、ウロボロスPraosのセキュリティ上の最低ラインとなります。\n※ノードを再起動すると初期化されますので適正値になるまで時間がかかります。",
   "gridPos": { "h": 6, "w": 1, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfThree",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "5 Second block fetch client block delay",
   "type": "stat",
   "description": "■ブロックの伝搬について\n1秒、3秒、5秒以内にブロックをダウンロードできたおおよその推定値\n95%のブロックを3秒以内にダウンロードしていれば、よく稼働しているノード指標となります。\n95%のブロックを5秒以内にダウンロードすることは、ウロボロスPraosのセキュリティ上の最低ラインとなります。\n※ノードを再起動すると初期化されますので適正値になるまで時間がかかります。",
   "gridPos": { "h": 6, "w": 1, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfFive ",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slots missed num",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotsMissedNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node timex max error seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "node_timex_maxerror_seconds * 1000",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rts_gc_wall_ms / 1000", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Disk usage rate",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes / node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Processor usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"prometheus\", mode=\"user\"}[1m]))",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Swap memory usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block fetch client late blocks",
   "type": "stat",
   "description": "■5秒以上後に到着したブロックの追跡\nミントされたはずのブロックが5秒以上後に到着したブロックを追跡します。",
   "gridPos": { "h": 5, "w": 1, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_lateblocks",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "stat",
   "description": "■チェーン上のフォーク数をカウント\nノードがスタートしてからのフォーク数。ブロック伝播遅延の影響で2秒前後のスロット間のスケジュールで発生",
   "gridPos": { "h": 5, "w": 1, "x": 1, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cardano_node_metrics_forks_int", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Block fetch client block delay",
   "type": "stat",
   "description": "■ブロック受信までの時間\nブロックがミントされるべきだったときから、ローカルのリレーがブロックを受信するまでの遅延を推定した時間\nこの指標には、コンセンサス/元帳がそのブロックを採用するまでの時間は含まれていません（採用されない可能性もあります）。",
   "gridPos": { "h": 5, "w": 1, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_s",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block latest count",
   "type": "bargauge",
   "description": "■リレーノードの有用性判定\n人気のないノードには0に近い値が与えられます。そして、非常に有用なノードには1以上の値が与えられます。\n値が0の場合、誰もあなたのリレーからブロックを取得していないことを意味します。\n1の値は、新しいブロックが作成されるたびに、誰かがそれを取得していることを意味します。\n2以上の値は、ミントされたブロックごとに、2つのノードがあなたからそのブロックをフェッチしていることを意味します。",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_served_block_latest_count_int[1h])/rate(cardano_node_metrics_blockNum_int[1h])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Chain density %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "System memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} transmit"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} write"
    }
   ]
  }
 ]
}